function [figure1]=createfigure(X1, Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13,T)
%CREATEFIGURE1(X1, Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data
%  Y6:  vector of y data
%  Y7:  vector of y data
%  Y8:  vector of y data
%  Y9:  vector of y data
%  Y10:  vector of y data
%  Y11:  vector of y data
%  Y12:  vector of y data
%  Y13:  vector of y data

%  Auto-generated by MATLAB on 26-Jun-2018 17:42:30

% Create figure
figure1 = figure('rend','painters','pos',[10 10 900 600]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.709264705882353 0.316420118343195 0.215735294117647]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_1$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[60 80]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot1 = subplot(3,7,4,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y2,'Parent',subplot1,'LineWidth',1,'Color',[0 0 1]);

% Create title
title('$\mathcal{N}_2$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot1,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot1,[60 80]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'Color',[0.678431391716003 0.921568632125854 1],'FontSize',12,...
    'LineWidth',1);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.588579881656805 0.709264705882353 0.316420118343195 0.215735294117647]);
hold(axes2,'on');

% Create plot
plot(X1,Y3,'Parent',axes2,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_3$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes2,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes2,[60 80]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.13 0.409632352941176 0.316420118343195 0.215735294117647]);
hold(axes3,'on');

% Create plot
plot(X1,Y4,'Parent',axes3,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_4$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes3,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes3,[60 80]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot2 = subplot(3,7,11,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y5,'Parent',subplot2,'LineWidth',1,'Color',[0 0 1]);

% Create title
title('$\mathcal{N}_5$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot2,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot2,[60 80]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'Color',[0.678431391716003 0.921568632125854 1],'FontSize',12,...
    'LineWidth',1);
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.588579881656805 0.409632352941176 0.316420118343195 0.215735294117647]);
hold(axes4,'on');

% Create plot
plot(X1,Y6,'Parent',axes4,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_6$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes4,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes4,[60 80]);
box(axes4,'on');
% Set the remaining axes properties
set(axes4,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot3 = subplot(3,7,15,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y7,'Parent',subplot3,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_7$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot3,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot3,[60 80]);
box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot4 = subplot(3,7,16,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X1,Y8,'Parent',subplot4,'LineWidth',1,'Color',[0 0 1]);
hold on, plot(X1,70*ones(length(X1),1),'r--','Parent',subplot4,'LineWidth',.5);

% Create title
title('$\mathcal{N}_8$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot4,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot4,[60 80]);
box(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'Color',[0.678431391716003 0.921568632125854 1],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot5 = subplot(3,7,17,'Parent',figure1);
hold(subplot5,'on');

% Create plot
plot(X1,Y9,'Parent',subplot5,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_9$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot5,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot5,[60 80]);
box(subplot5,'on');
% Set the remaining axes properties
set(subplot5,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot6 = subplot(3,7,18,'Parent',figure1);
hold(subplot6,'on');

% Create plot
plot(X1,Y10,'Parent',subplot6,'LineWidth',1,'Color',[0 0 1]);
hold on, plot(X1,70*ones(length(X1),1),'r--','Parent',subplot6,'LineWidth',.5);

% Create title
title('$\mathcal{N}_{10}$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot6,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot6,[60 80]);
box(subplot6,'on');
% Set the remaining axes properties
set(subplot6,'Color',[0.678431391716003 0.921568632125854 1],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot7 = subplot(3,7,19,'Parent',figure1);
hold(subplot7,'on');

% Create plot
plot(X1,Y11,'Parent',subplot7,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_{11}$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot7,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot7,[60 80]);
box(subplot7,'on');
% Set the remaining axes properties
set(subplot7,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot8 = subplot(3,7,20,'Parent',figure1);
hold(subplot8,'on');

% Create plot
plot(X1,Y12,'Parent',subplot8,'LineWidth',1,'Color',[0 0 1]),
hold on, plot(X1,70*ones(length(X1),1),'r--','Parent',subplot8,'LineWidth',.5);

% Create title
title('$\mathcal{N}_{12}$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot8,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot8,[60 80]);
box(subplot8,'on');
% Set the remaining axes properties
set(subplot8,'Color',[0.678431391716003 0.921568632125854 1],'FontSize',12,...
    'LineWidth',1);
% Create subplot
subplot9 = subplot(3,7,21,'Parent',figure1);
hold(subplot9,'on');

% Create plot
plot(X1,Y13,'Parent',subplot9,'LineWidth',1,'Color',[0 0.498039215803146 0]);

% Create title
title('$\mathcal{N}_{13}$','LineWidth',1,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot9,[0 T]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot9,[60 80]);
box(subplot9,'on');
% Set the remaining axes properties
set(subplot9,'Color',[0.600000023841858 1 0.600000023841858],'FontSize',12,...
    'LineWidth',1);
% Create textbox
annotation(figure1,'textbox',...
    [0.435215946843855 0.95229341248838 0.215026606879599 0.0437125755355744],...
    'String',{'Temperature Profile $^\circ C$'},...
    'LineStyle','none',...
    'Interpreter','latex',...
    'FontSize',12,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.480897009966778 0.00618562805723998 0.0833796014795478 0.0437125755355744],...
    'String',{'Time [s]'},...
    'LineStyle','none',...
    'Interpreter','latex',...
    'FontSize',12,...
    'FitBoxToText','off');

